### ISSUE TITLE
akka typed support

### ISSUE THREAD

**Issue by KannarFr** [mkroli/dns4s#18]
Hi @mkroli,

Thanks for this nice project. There is a quick way to support akka typed (or compatibility to run using the akka typed system, maybe using classicSystem)?

```java
java.lang.UnsupportedOperationException: cannot create top-level actor [dns4s] from the outside on ActorSystem with custom user guardian
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:895)
	at com.github.mkroli.dns4s.akka.DnsExtension.<init>(DnsExtension.scala:50)
	at com.github.mkroli.dns4s.akka.Dns$.createExtension(DnsExtension.scala:34)
	at com.github.mkroli.dns4s.akka.Dns$.createExtension(DnsExtension.scala:33)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at com.github.mkroli.dns4s.akka.Dns$.apply(DnsExtension.scala:33)
	at akka.io.IO$.apply(IO.scala:26)
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:152)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:131)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:107)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by KannarFr** [comment]
(Without creating a dedicated ActorSystem).

**Comment by mkroli** [comment]
To create a DNS server the following sample works for me (adapted [examples/simple/.../DnsServer.scala](../blob/master/examples/simple/src/main/scala/com/github/mkroli/dns4s/examples/simple/DnsServer.scala)):
```scala
import akka.actor.typed._
import akka.actor.typed.scaladsl._
import akka.actor.typed.scaladsl.adapter._
import akka.io.IO
import akka.pattern._
import akka.util.Timeout
import akka.{actor => classic}
import com.github.mkroli.dns4s.Message
import com.github.mkroli.dns4s.akka.Dns
import com.github.mkroli.dns4s.dsl._

import scala.concurrent.duration.DurationInt
import scala.language.postfixOps

class DnsHandlerActor(typed: ActorRef[DnsQuery]) extends classic.Actor {
  override def receive = {
    case msg: Message => typed ! DnsQuery(sender, msg)
  }
}

case class DnsQuery(sender: akka.actor.ActorRef, msg: Message)

object TypedDnsHandlerActor {
  val behavior: Behavior[DnsQuery] =
    Behaviors.setup { _ =>
      Behaviors.receive[DnsQuery] {
        case (_, DnsQuery(sender, Query(q) ~ Questions(QName(host) ~ TypeA() :: Nil))) =>
          sender ! Response(q) ~ Answers(RRName(host) ~ ARecord("1.2.3.4"))
          Behaviors.same
      }
    }
}

object DnsServer extends App {
  implicit val system = classic.ActorSystem("DnsServer")
  implicit val timeout = Timeout(5 seconds)
  val typedDnsHandlerActor = system.spawn(TypedDnsHandlerActor.behavior, "dns")
  IO(Dns) ? Dns.Bind(system.actorOf(classic.Props(classOf[DnsHandlerActor], typedDnsHandlerActor)), 5354)
}
```
Probably it makes sense to create another integration layer for typed actors instead.

**Comment by KannarFr** [comment]
Thanks!

**Comment by KannarFr** [comment]
Thanks for the reply. In fact, my issue is about using an existing typed ActorSystem for the DNS server itself. I already have a typed handler.  

If we can't yet, I will create a dedicated ActorSystem as you wrote in the object DnsServer.
