### ISSUE TITLE
Error while running client example

### ISSUE THREAD

**Issue by pansophism** [mkroli/dns4s#4]
When I try to run the example : https://github.com/mkroli/dns4s/blob/master/examples/simple-client/src/main/scala/com/github/mkroli/dns4s/examples/simple/client/DnsClient.scala

, the following message was encountered. Any idea?

Exception in thread "main" java.lang.NoSuchMethodError: akka.pattern.AskableActorRef$.$qmark$default$3$extension(Lakka/actor/ActorRef;Ljava/lang/Object;)Lakka/actor/ActorRef;
	at com.github.mkroli.dns4s.examples.simple.client.DnsClient$.delayedEndpoint$com$github$mkroli$dns4s$examples$simple$client$DnsClient$1(DnsClient.scala:36)
	at com.github.mkroli.dns4s.examples.simple.client.DnsClient$delayedInit$body.apply(DnsClient.scala:31)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.github.mkroli.dns4s.examples.simple.client.DnsClient$.main(DnsClient.scala:31)
	at com.github.mkroli.dns4s.examples.simple.client.DnsClient.main(DnsClient.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by mkroli** [comment]
For me the example works using ```sbt run```.
Is there any way for you to find out which version of akka is actually used when you run the example?
